### ISSUE TITLE
There are some weird things？

### ISSUE THREAD

**Issue by liqiang311** [clausmichele/ViDeNN#1]
Thanks for your trained model, and I run it on my own video.

As a result, there are some weird things on the image, as shown in the figure.

noisy![noisy](https://user-images.githubusercontent.com/19705210/48187875-4d29d280-e377-11e8-95bd-92f8435fffe7.png)
denoised![denoised](https://user-images.githubusercontent.com/19705210/48187902-5a46c180-e377-11e8-827e-66da050f04c1.png)
noisy![noisy](https://user-images.githubusercontent.com/19705210/48187943-7185af00-e377-11e8-9a20-74d45c521338.png)
denoise![denoise](https://user-images.githubusercontent.com/19705210/48187983-82cebb80-e377-11e8-9d03-7438afe2010a.png)

What's that?  Can you help me?

**Comment by clausmichele** [comment]
Hi!
As far as I see those images/frames contain artifacts due to compression, which of course can be seen as noise, but it was not a type of degradation that was in my training set. Maybe that's the explanation.
I will try to denoise those two images on my pc and see if there are differences.

**Comment by liqiang311** [comment]
Yes, you are correct, the sequence I am using is coded and there is quantization noise.

I have used the original sequence to test, and the bad phenomenon still exists, but it is much better.

denoised
![image](https://user-images.githubusercontent.com/19705210/48190816-93366480-e37e-11e8-996e-4c15ddae3095.png)
noisy
![image](https://user-images.githubusercontent.com/19705210/48190833-a0535380-e37e-11e8-9602-11314cbc9d7c.png)

**Comment by clausmichele** [comment]
So, I've tried your noisy input and I don't get any strange output, tested with both checkpoint I provide.
Which tensorflow version are you using?
NOISY:
![1](https://user-images.githubusercontent.com/31700619/48195722-b518f280-e350-11e8-8396-d036b6243769.png)
DENOISED:
![0001](https://user-images.githubusercontent.com/31700619/48195755-c530d200-e350-11e8-9a5e-51fb46995d34.png)

**Comment by liqiang311** [comment]
Thank you for your testing.

- Python version: 3.6.4
- Tensorflow version: tensorflow-gpu (1.4.0)

I only change the "xrange" to "range" in code. And I am running a series of images.

**Comment by clausmichele** [comment]
The only think I can try is to use your data on my machine, attach your files here if you want.

**Comment by lalithnag** [comment]
Hi, thanks a lot for the trained model! 

I too have the same issue. Is it may be because the model is overfitting, as it has not seen these artefacts in the training data?

* Python 3.6.7
* tensorflow==1.12.0

(I am sending you the images via mail, as I cannot put it up online). Please also note that I can see these artefacts in all the frames!

Thanks!

**Comment by clausmichele** [comment]
If you use the gaussian trained checkpoint you won't have any of those weird results.
Just run it with: python main.py --ckpt_dir=./ckpt_vidcnn-g

**Comment by lalithnag** [comment]
Thank you, I'm having a problem with running
`python main.py --ckpt_dir=./ckpt_vidcnn-g`
so I've opened this [new issue](https://github.com/clausmichele/VidCNN---Learning-Blind-Video-Denoising/issues/3).

**Comment by MexWayne** [comment]
> The only think I can try is to use your data on my machine, attach your files here if you want.

Hi I‘m so interested in your work and I meet the same problem，it's the input png which is compressed will cause these artifacts？

![image](https://github.com/clausmichele/ViDeNN/assets/9520310/9fd6aa2f-88da-47f1-a602-0bc41c110a11)
