### ISSUE TITLE
Not work for single image

### ISSUE THREAD

**Issue by MaShaoming** [clausmichele/ViDeNN#10]
hi~

in you paper ,you said "_this architecture can achieve state-of-art results for Gaussian denoising_" in **3.1. Spatial Denoising CNN**. But I received weak denoising effect while only try three frames of same images with Gaussian noise.

Could you explain this situation, thanks very much!

**Comment by clausmichele** [comment]
Hi, can you let me know some details?
1. How did you add gaussian noise on your data?
Please note that this network has been trained with gaussian noise generated by the formula defined in [add_noise_spatialCNN.py](https://github.com/clausmichele/ViDeNN/blob/master/Spatial-CNN/add_noise_spatialCNN.py) as 

```
def gaussian_noise(sigma,image):
	gaussian = np.random.normal(0,sigma,image.shape)
	noisy_image = np.zeros(image.shape, np.float32)
	noisy_image = image + gaussian
	noisy_image = np.clip(noisy_image,0,255)
	noisy_image = noisy_image.astype(np.uint8)
	return noisy_image
```
If you define in a different way (e.g. without clipping) the results will be worse. You can try to fine tune the existing checkpoint or retrain from scratch if you want to try a different AWGN implementation.

2. Were the images noise free or jpeg compressed?
3. Which checkpoint did you use for testing?

Cheers

**Comment by MaShaoming** [comment]
hi clausmichele,

the root cause is the image's format is JPEG and I just searched gaussian noise image from google.
it works well after adding noise with your method.

really appreciate for your reply, best wishes !
