### ISSUE TITLE
Denoise code

### ISSUE THREAD

**Issue by bkumardevan07** [clausmichele/ViDeNN#13]
I see that in your code you are using 
``
noisyin2[0,:,:,0:3] = out[0,0]
noisyin2[0,:,:,3:6] = out[0,0]
noisyin2[0,:,:,6:] = out[0,1]
``

in class Videnn, denoise...
why not adding the third frame output and repeating 1st frame???

**Comment by clausmichele** [comment]
I don't understand the issue, could you clarify? That part is run only once for the first frames.
