### ISSUE TITLE
Strange artefact

### ISSUE THREAD

**Issue by Entretoize** [clausmichele/ViDeNN#20]
I finally been able to train you models on windows and to test a video denoising and I get those strange circle artefact:

https://ibb.co/v1nZY5J

Do you see what is causing them ?

**Comment by clausmichele** [comment]
Please have a look at other closed issues about this:
https://github.com/clausmichele/ViDeNN/issues/1
https://github.com/clausmichele/ViDeNN/issues/7
https://github.com/clausmichele/ViDeNN/issues/8
