### ISSUE TITLE
Improve documentation for artists

### ISSUE THREAD

**Issue by Tilix4** [clausmichele/ViDeNN#21]
Hi!

I'm a video artist and tool developer but I've never run a CNN before. Your work is very powerful and I'd like to contribute in my scope. 
I've finally managed to make it work after a long roaming time. And the issues I've faced are mostly about a not very user friendly documentation. 

I'd propose some improvements, if you accept them I can propose a PR later. 

### Setup
- Precise we must use a python <= 3.6 because tensorflow 1.4 isn't available either way. 
- Explicitly say we don't have to train the model ourselves, I've spent a lot of time trying to achieve this step before understanding everything is already there. And I couldn't guess because I'm not familiar with all of these concepts and files. 
- Create a `requirements.txt` file for pip installation.

### Runtime
- Add a warning if the GPU has been selected but because of not enough memory available, it fell back on the CPU. 

NB: I've faced some issues with the paths using the command-line. I'd like to propose a little refactor using `pathlib`, which makes it only python3 but is efficient. But it's for another issue if you agree.

**Comment by clausmichele** [comment]
Hi! Thanks for your interest! You are right, the documentation is not brilliant. Unfortunately I don't have time to further develop this project, but I would be happy to merge the improvements you are proposing with a PR.
May I ask you what you are trying to do with this code/CNN ? I'd love to see what other people can do with my work!

**Comment by Tilix4** [comment]
I'll propose something then!

We shot a short film with a sony alpha 7 mk II in Slog2 but in low light environment and this is a bit noisy for one shot, after grading and exported compressed it becomes very noisy and feels dirty, then I'd like to clean the input.

I think it's important to make these kind of algorithm accessible to independant artists because it helps them having more professional renders and then a better visibility :)
