### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by chendengshuai** [clausmichele/ViDeNN#4]

**Comment by chendengshuai** [comment]
hi, your work is very good! thanks to share your idea and part of code, but i have a question that could i see your train code?

**Comment by Integraali10** [comment]
This issue is still relevant! It would be wonderful to see train code.

**Comment by clausmichele** [comment]
I will try to wrap up the code and publish it as soon as possible.
Notice that the network is trained in two separate steps, one for the spatial part and one for the temporal part.

**Comment by xuehanwen** [comment]
For some scene tests, the effect is obvious, can you provide training code for learning?

**Comment by clausmichele** [comment]
train code released, closing
