### ISSUE TITLE
There is questions about adding noise

### ISSUE THREAD

**Issue by chengerr** [clausmichele/ViDeNN#5]
Hello ! Your work is excellent !  I have some questions about adding noise to clean image.  Should I first change the range[0,255] to [0,1] ?  And then add noise at pixel level?

**Comment by clausmichele** [comment]
Hi, thank you!
Yes, you can first normalize the image in range [0,1] and then add the gaussian (for example) noise.
After that, remember to clip the pixel values again in range [0,1].

**Comment by chengerr** [comment]
Oh I get it ! It's so kind of you ! And does clipping means substracting directly ?


------------------ 原始邮件 ------------------
发件人: "clausmichele"<notifications@github.com>;
发送时间: 2019年3月14日(星期四) 晚上11:34
收件人: "clausmichele/VidCNN---Learning-Blind-Video-Denoising"<VidCNN---Learning-Blind-Video-Denoising@noreply.github.com>;
抄送: "miumiu"<1786715287@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [clausmichele/VidCNN---Learning-Blind-Video-Denoising] There isquestions about adding noise (#5)




Hi, thank you!
 Yes, you can first normalize the image in range [0,1] and then add the gaussian (for example) noise.
 After that, remember to clip the pixel values again in range [0,1].

**Comment by clausmichele** [comment]
After adding noise to the image, it could contain values below 0 and over 1.
Clipping means setting what is < 0 equal to 0 and what is > 1 equal to 1.
