### ISSUE TITLE
The difference between ckpt_vidcnn-g & ckpt_vidcnn?

### ISSUE THREAD

**Issue by conson0214** [clausmichele/ViDeNN#6]
is ckpt_vidcnn-g trained with AWGN and ckpt_vidcnn with Real world noise?
If so, what noise level used in training ckpt-vidcnn-g?

**Comment by clausmichele** [comment]
ckpt_vidcnn-g is trained with AWGN only, with standard deviation in range [0:55].
ckpt_vidcnn uses a mixture of noises, containing AWGN, realistic and low-light noise.
