### ISSUE TITLE
About the Denoised Picture

### ISSUE THREAD

**Issue by z870609382** [clausmichele/ViDeNN#7]
There are a number of shining white spots in most of pictures in file'denoised' ,I want to know the reasons why they exist.

**Comment by WangLiwen1994** [comment]
I also meet the same problem.

**Comment by clausmichele** [comment]
As stated in the Readme:
_Important: the network has not been trained for general-purpose denoising of compressed (h264, h265 ecc) videos. If the output includes some artifacts try to use the other checkpoint, modifying the last line of the script with --checkpoint_dir='./ckpt_vidcnn-g'._

You can also train your own model, the code has been released. Let me know if you need help with the training part.

**Comment by WangLiwen1994** [comment]
> As stated in the Readme:
> _Important: the network has not been trained for general-purpose denoising of compressed (h264, h265 ecc) videos. If the output includes some artifacts try to use the other checkpoint, modifying the last line of the script with --checkpoint_dir='./ckpt_vidcnn-g'._
> 
> You can also train your own model, the code has been released. Let me know if you need help with the training part.

Thanks for your kind reply. Using another checkpoint has solved my problem.

**Comment by sunyclj** [comment]
@clausmichele Hi,i will train model in my dataset,but I ran into some problems.in your paper, 'The dataset is randomly divided in two parts, 70% for training and 30% for testing. Half of the images are being added with AWGN with σ=[0,55]. The second half are processed with equation 2 which is the realistic noise model, with Analog Gain Ag=[0,64] and Digital Gain Dg=[0,32]',according to this,the code is written as follows:
![image](https://user-images.githubusercontent.com/44860428/164132379-da38c469-c920-4cab-adb7-29b781ad3a80.png)
However, after adding noise to the picture, the ckpt_videnn model is used to remove noise, which cannot be restored.As show,the left is original image,the middle is add noise image,the right is denoise image using the ckpt_videnn model.
![0000](https://user-images.githubusercontent.com/44860428/164133747-6d008e01-cb3a-48b3-be45-d330e2011083.png)
![0000](https://user-images.githubusercontent.com/44860428/164133842-b16e8a70-a6ab-4ec7-b86a-c47034b955b8.png)
![Uploading 0000.png…]()

**Comment by clausmichele** [comment]
Hi @sunyclj. Did you train the model yourself or are you trying to re-use my old checkpoint files? By the way, the third image is not visible.

**Comment by sunyclj** [comment]
@clausmichele i want to use my data to train new model.the third image is the first picture with realistic noise,as follow:
![0000](https://user-images.githubusercontent.com/44860428/164174551-0b3eb582-6796-4cab-8cc3-74979daab2b0.png)
the sencond is denoise image using the ckpt_videnn model.
