### ISSUE TITLE
Artifacts when denoising AWGN

### ISSUE THREAD

**Issue by m-tassano** [clausmichele/ViDeNN#8]
Hi! I'm getting loads of artifacts when denoising sequences with AWGN (see a couple of examples of sequences from the DAVIS dataset below) Is this normal? Thanks

![image](https://user-images.githubusercontent.com/29971778/68671947-5243d380-052f-11ea-9c84-b9c4edd5e7ca.png)

![image](https://user-images.githubusercontent.com/29971778/68671983-5f60c280-052f-11ea-945d-72aa3847a48f.png)

**Comment by clausmichele** [comment]
I am currently working on a new version of the code with the training part, since I guess there are some problems with tensorflow and the stored weights. As soon as I finish I will release it here.

**Comment by clausmichele** [comment]
> Hi! I'm getting loads of artifacts when denoising sequences with AWGN (see a couple of examples of sequences from the DAVIS dataset below) Is this normal? Thanks
> 
> ![image](https://user-images.githubusercontent.com/29971778/68671947-5243d380-052f-11ea-9c84-b9c4edd5e7ca.png)
> 
> ![image](https://user-images.githubusercontent.com/29971778/68671983-5f60c280-052f-11ea-945d-72aa3847a48f.png)

Could you please share with me the data you tried to denoise? How did you add AWGN?
I will use it for testing..

**Comment by m-tassano** [comment]
I used different sources, for example the DAVIS testset
<https://data.vision.ee.ethz.ch/csergi/share/davis/DAVIS-2017-test-dev-480p.zip>
and
some sequences from the Derf dataset downscaled to 960x540 (e.g. crowd_run
<ftp://vqeg.its.bldrdoc.gov/HDTV/SVT_MultiFormat/> )

For the AWGN, I modified the definition of the noisy, noisy1, noisy2 vars
like the following

noisy = test + np.random.normal(loc=.0, scale=(sigma / 255.),
size=test.shape)

**Comment by clausmichele** [comment]
I guess the main difference is the clipping step which is missing. For training I used:
```
def gaussian_noise(sigma,image):
	gaussian = np.random.normal(0,sigma,image.shape)
	noisy_image = np.zeros(image.shape, np.float32)
	noisy_image = image + gaussian
	noisy_image = np.clip(noisy_image,0,255)
	noisy_image = noisy_image.astype(np.uint8)
	return noisy_image
```

**Comment by m-tassano** [comment]
OK, I understand, but if you clip the image after adding Gaussian noise,
you modify the distribution of the input noise. In other words, noisy_image
won't have Gaussian noise any more.

**Comment by clausmichele** [comment]
True, but since it is not possible to have a real image where the values are higher than 255 (or 1) or lower than 0, it makes sense to me to clip the image.
If I store a noisy image/video in a file instead of a local variable, they will be clipped.
You could claim that AWGN is not a realistic noise type, so why bother if it can be stored in a real image.
However, this project was born to treat different kind of noise and was not specificly designed for AWGN.
Let me know if clipping the images solves the problem, if not I'll investigate further.

**Comment by m-tassano** [comment]
Ok, I see. Actually, in some cases you would like to denoise non clipped
images, e.g. raw images or images saved as tiff. Any way, I understand your
motivations for clipping images. On the other hand, your publication does
compare your method to other denoising algorithms for AWGN. Bare in mind
that methods such as BM3D or DnCNN haven't been designed/trained for
clipped images, so their performance will certainly suffer. This makes the
comparison in your publication not really fair/accurate.

In any case, thank you for your reply and your time. I will let you know if
artifacts still appear even after clipping.
